Public class Test {
    /*public void marks(){ 

	integer count=1, coun=99, maxnum=5;
        while(count<=5)
        {
            system.debug('wecome vijay');
            count++;
        }  
        while (coun <= 10)
        {
            system.debug('even numbers is '+coun);
            coun +=2;
        }
        while (count <=10)
        {
            system.debug(maxnum + '*' + count + '=' + (count*maxnum));
            count++;
		}
        while(coun >= 1)
        {
            system.debug('odd numbers is '+ coun);
            coun-=2;
        }
        do
        {
            system.debug('odd nubers is '+coun);
            coun-=2;
        }while(coun >=1);

        for( Integer i=0; count <= 30; count++)
        {
            system.debug(maxnum + '*' + count + '=' + (maxnum*count));
        }
        
        integer[] count = new integer[10];
        count= new integer[] {10,20,30,40,50,60,70,80,90,100};
            system.debug(count);
        system.debug(count[0]);
        for (integer i=0; i<=5; i++)
        {
            system.debug(count[i]);
        }
        for(integer i:count){
            system.debug(i[3]);
        }
    } */
    Public static void practice()
    {
        string[] cal = new string[10]{'ram','suresh','jayaram','sampath','battu','jugirijinganiya'};

        system.debug('the array elements are..:'+cal);
    } 
}